
#define PIDS_SUPPORT_01_20                         0x00
#define MONITOR_STATUS_SINCE_DTCS_CLEARED          0x01
#define FREEZE_DTC                                 0x02
#define FUEL_SYSTEM_STATUS                         0x03
#define CALCULATED_ENGINE_LOAD                     0x04
#define ENGINE_COOLANT_TEMPERATURE                 0x05
#define SHORT_TERM_FUEL_TRIM_BANK_1                0x06
#define LONG_TERM_FUEL_TRIM_BANK_1                 0x07
#define SHORT_TERM_FUEL_TRIM_BANK_2                0x08
#define LONG_TERM_FUEL_TRIM_BANK_2                 0x09
#define FUEL_PRESSURE                              0x0a
#define INTAKE_MANIFOLD_ABSOLUTE_PRESSURE          0x0b
#define ENGINE_RPM                                 0x0c
#define VEHICLE_SPEED                              0x0d
#define TIMING_ADVANCE                             0x0e
#define AIR_INTAKE_TEMPERATURE                     0x0f
#define MAF_AIR_FLOW_RATE                          0x10
#define THROTTLE_POSITION                          0x11
#define COMMANDED_SECONDARY_AIR_STATUS             0x12
#define OXYGEN_SENSORS_PRESENT_IN_2_BANKS          0x13
#define OXYGEN_SENSOR_1_SHORT_TERM_FUEL_TRIM       0x14
#define OXYGEN_SENSOR_2_SHORT_TERM_FUEL_TRIM       0x15
#define OXYGEN_SENSOR_3_SHORT_TERM_FUEL_TRIM       0x16
#define OXYGEN_SENSOR_4_SHORT_TERM_FUEL_TRIM       0x17
#define OXYGEN_SENSOR_5_SHORT_TERM_FUEL_TRIM       0x18
#define OXYGEN_SENSOR_6_SHORT_TERM_FUEL_TRIM       0x19
#define OXYGEN_SENSOR_7_SHORT_TERM_FUEL_TRIM       0x1a
#define OXYGEN_SENSOR_8_SHORT_TERM_FUEL_TRIM       0x1b
#define OBD_STANDARDS_THIS_VEHICLE_CONFORMS_TO     0x1c
#define OXYGEN_SENSORS_PRESENT_IN_4_BANKS          0x1d
#define AUXILIARY_INPUT_STATUS                     0x1e
#define RUN_TIME_SINCE_ENGINE_START                0x1f
#define PIDS_SUPPORT_21_40                         0x20
#define DISTANCE_TRAVELED_WITH_MIL_ON              0x21
#define FUEL_RAIL_PRESSURE                         0x22
#define FUEL_RAIL_GAUGE_PRESSURE                   0x23
#define OXYGEN_SENSOR_1_FUEL_AIR_EQUIVALENCE_RATIO 0x24
#define OXYGEN_SENSOR_2_FUEL_AIR_EQUIVALENCE_RATIO 0x25
#define OXYGEN_SENSOR_3_FUEL_AIR_EQUIVALENCE_RATIO 0x26
#define OXYGEN_SENSOR_4_FUEL_AIR_EQUIVALENCE_RATIO 0x27
#define OXYGEN_SENSOR_5_FUEL_AIR_EQUIVALENCE_RATIO 0x28
#define OXYGEN_SENSOR_6_FUEL_AIR_EQUIVALENCE_RATIO 0x29
#define OXYGEN_SENSOR_7_FUEL_AIR_EQUIVALENCE_RATIO 0x2a
#define OXYGEN_SENSOR_8_FUEL_AIR_EQUIVALENCE_RATIO 0x2b
#define COMMANDED_EGR                              0x2c
#define EGR_ERROR                                  0x2d
#define COMMANDED_EVAPORATIVE_PURGE                0x2e
#define FUEL_TANK_LEVEL_INPUT                      0x2f
#define WARM_UPS_SINCE_CODES_CLEARED               0x30
#define DISTANCE_TRAVELED_SINCE_CODES_CLEARED      0x31
#define EVAP_SYSTEM_VAPOR_PRESSURE                 0x32
#define ABSOLULTE_BAROMETRIC_PRESSURE              0x33
#define CATALYST_TEMPERATURE_BANK_1_SENSOR_1       0x3c
#define CATALYST_TEMPERATURE_BANK_2_SENSOR_1       0x3d
#define CATALYST_TEMPERATURE_BANK_1_SENSOR_2       0x3e
#define CATALYST_TEMPERATURE_BANK_2_SENSOR_2       0x3f
#define PIDS_SUPPORT_41_60                         0x40
#define MONITOR_STATUS_THIS_DRIVE_CYCLE            0x41
#define CONTROL_MODULE_VOLTAGE                     0x42
#define ABSOLUTE_LOAD_VALUE                        0x43
#define FUEL_AIR_COMMANDED_EQUIVALENCE_RATE        0x44
#define RELATIVE_THROTTLE_POSITION                 0x45
#define AMBIENT_AIR_TEMPERATURE                    0x46
#define ABSOLUTE_THROTTLE_POSITION_B               0x47
#define ABSOLUTE_THROTTLE_POSITION_C               0x48
#define ABSOLUTE_THROTTLE_POSITION_D               0x49
#define ABSOLUTE_THROTTLE_POSITION_E               0x4a
#define ABSOLUTE_THROTTLE_POSITION_F               0x4b
#define COMMANDED_THROTTLE_ACTUATOR                0x4c
#define TIME_RUN_WITH_MIL_ON                       0x4d
#define TIME_SINCE_TROUBLE_CODES_CLEARED           0x4e
#define FUEL_RAIL_ABSOLUTE_PRESSURE                0x59
#define RELATIVE_ACCELERATOR_PEDAL_POSITTION       0x5a
#define HYBRID_BATTERY_PACK_REMAINING_LIFE         0x5b
#define ENGINE_OIL_TEMPERATURE                     0x5c
#define FUEL_INJECTION_TIMING                      0x5d
#define ENGINE_FUEL_RATE                           0x5e
